const https = require('https');

class EvoMapConnector {
  constructor(config) {
    this.config = config;
    this.baseUrl = config.evomapUrl;
    this.nodeId = config.nodeId;
    this.headers = {
      'Content-Type': 'application/json'
    };
  }

  async connect() {
    try {
      // 测试连接
      const status = await this.getNodeStatus();
      if (status.online) {
        console.log('✅ EvoMap 连接成功');
        return { success: true, status };
      } else {
        console.log('⚠️ EvoMap 节点状态异常');
        return { success: false, status };
      }
    } catch (error) {
      console.error('❌ EvoMap 连接失败:', error.message);
      return { success: false, error: error.message };
    }
  }

  async getNodeStatus() {
    try {
      const response = await this.request({
        path: '/a2a/directory',
        method: 'GET'
      });
      
      // 查找我们的节点
      if (response.nodes) {
        const ourNode = response.nodes.find(node => node.node_id === this.nodeId);
        if (ourNode) {
          return {
            online: true,
            nodeId: ourNode.node_id,
            reputation: ourNode.reputation_score,
            totalPublished: ourNode.total_published,
            lastSeen: ourNode.last_seen_at
          };
        }
      }
      
      return {
        online: false,
        nodeId: this.nodeId,
        error: 'Node not found in directory'
      };
    } catch (error) {
      console.error('获取节点状态失败:', error.message);
      return {
        online: false,
        nodeId: this.nodeId,
        error: error.message
      };
    }
  }

  async fetchTasks() {
    try {
      const response = await this.request({
        path: '/a2a/fetch?include_tasks=true',
        method: 'POST',
        body: {
          protocol: 'gep-a2a',
          protocol_version: '1.0.0',
          message_type: 'fetch',
          message_id: `msg_${Date.now()}_${Math.floor(Math.random() * 10000)}`,
          sender_id: this.nodeId,
          timestamp: new Date().toISOString(),
          payload: {
            include_tasks: true,
            filters: {
              min_reputation: 0
            }
          }
        }
      });
      
      return response.tasks || [];
    } catch (error) {
      console.error('获取任务失败:', error.message);
      return [];
    }
  }

  async publishAsset(assets, taskId) {
    try {
      const response = await this.request({
        path: '/a2a/publish',
        method: 'POST',
        body: {
          protocol: 'gep-a2a',
          protocol_version: '1.0.0',
          message_type: 'publish',
          message_id: `msg_${Date.now()}_${Math.floor(Math.random() * 10000)}`,
          sender_id: this.nodeId,
          timestamp: new Date().toISOString(),
          payload: {
            assets: assets,
            task_id: taskId,
            solution_summary: 'Generated by 绿茶 CGO 智能体'
          }
        }
      });
      
      return response;
    } catch (error) {
      console.error('发布资产失败:', error.message);
      throw error;
    }
  }

  async completeTask(taskId, assetId) {
    try {
      const response = await this.request({
        path: '/task/complete',
        method: 'POST',
        body: {
          task_id: taskId,
          asset_id: assetId,
          node_id: this.nodeId
        }
      });
      
      return response;
    } catch (error) {
      console.error('完成任务失败:', error.message);
      throw error;
    }
  }

  async request(options) {
    const {
      path,
      method = 'GET',
      body = null
    } = options;

    const requestOptions = {
      hostname: new URL(this.baseUrl).hostname,
      port: 443,
      path: path,
      method: method,
      headers: {
        ...this.headers,
        'Content-Length': body ? Buffer.byteLength(JSON.stringify(body)) : 0
      }
    };

    return new Promise((resolve, reject) => {
      const req = https.request(requestOptions, (res) => {
        let data = '';
        res.on('data', (chunk) => {
          data += chunk;
        });
        res.on('end', () => {
          try {
            const parsed = JSON.parse(data);
            if (res.statusCode >= 200 && res.statusCode < 300) {
              resolve(parsed);
            } else {
              reject(new Error(`HTTP ${res.statusCode}: ${JSON.stringify(parsed)}`));
            }
          } catch (parseError) {
            reject(new Error(`Failed to parse response: ${parseError.message}`));
          }
        });
      });

      req.on('error', (error) => {
        reject(error);
      });

      if (body) {
        req.write(JSON.stringify(body));
      }
      req.end();
    });
  }

  async getAssetStatus(assetId) {
    try {
      const response = await this.request({
        path: `/a2a/asset/${encodeURIComponent(assetId)}`,
        method: 'GET'
      });
      return response;
    } catch (error) {
      console.error('获取资产状态失败:', error.message);
      return null;
    }
  }

  async getNodeStats() {
    try {
      const directory = await this.request({
        path: '/a2a/directory',
        method: 'GET'
      });
      
      const node = directory.nodes.find(n => n.node_id === this.nodeId);
      if (node) {
        return {
          nodeId: node.node_id,
          reputation: node.reputation_score,
          totalPublished: node.total_published,
          totalPromoted: node.total_promoted,
          carbonTaxRate: node.carbon_tax_rate,
          lastSeen: node.last_seen_at
        };
      }
      
      return null;
    } catch (error) {
      console.error('获取节点统计失败:', error.message);
      return null;
    }
  }
}

module.exports = EvoMapConnector;