// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owsqargbjkdgpjciszyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93c3FhcmdiamtkZ3BqY2lzenlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5MjgzMTYsImV4cCI6MjA4MzUwNDMxNn0.5JMcr0po0GmFbPKAvQnSmP2bYk-2D5tHtcNchmkiIck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safe localStorage wrapper for SSR
const safeLocalStorage = {
  getItem: (key: string) => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem(key);
    }
    return null;
  },
  setItem: (key: string, value: string) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(key, value);
    }
  },
  removeItem: (key: string) => {
    if (typeof window !== 'undefined') {
      localStorage.removeItem(key);
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeLocalStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});
